### ISSUE TITLE
Use MikePurvis fix for recent CMake support

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-o/catkin#1]
For some reason I didnt succeed to open a PR towards this fork.

To reduce the amount of deprecation warnings while building ROS 1 packages on recent platforms it would be great to integrate this PR https://github.com/ros/catkin/pull/1195 from @mikepurvis into the ros-o version.

WDYT ?

**Comment by mikaelarguedas** [comment]
@rhaschke @v4hn what do you think about this ? Is this considered too cosmetic (as catkin can run without errors without it) to be included in the ros-o version of catkin ?

**Comment by rhaschke** [comment]
Thanks for pinging me. This looks reasonable at first sight, but I will have a deeper look later.

**Comment by rhaschke** [comment]
Merged: 5a4540c

**Comment by v4hn** [comment]
Also merged in [Debian ros-catkin 0.8.10-17](https://salsa.debian.org/science-team/ros-catkin/-/commit/00b1bf68ad537becb079f25d9387c81f2117d0b2).
